---
description: "A journey of the peaks and valleys of health, healing, and hope."
email: laura@h3withlaura.com
facebook_URL: "https://www.facebook.com/lauramsanders/"
font-awesome-icon-logo: ~
github_username: ~
instagram_username: lauramsanders
logo-image-url: /images/android-chrome-192x192_Logo.png
markdown: kramdown
permalink: "/:categories/:year/:month/:day/:title:output_ext"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
staticman_url: "https://h3withlaura.herokuapp.com/v2/entry/rockmonkey4004/rockmonkey4004.github.io/master/comments"

reCaptcha:
  secret: Mk0ByvDGXGV6EO5yZC5GlFmXm/0vjcy5ZW0ZDuabOGeixPzi8w5cxCSgrTfJijiAbuddFUZuHFDoi1XTIRA93yyq9GWJ9nWPlw425g/Y4t15dqtQ5a5/tI3LqEDewwRXQf1QiB1UDSAadW8PzWZ97fGo7sRdi1atxog2qNdj7juEZHtdaPy/aBQWbETqHUtTrYlUNeisC54tZzxvBjB17badbcRW/GskW5JCHpOXkeFTGk8XLRrF/DgQMoj351Gy4yJjWGawQtsT1gHdyTG/V8H9QhDs08uKKoIfq8hdVYHpFYbCX6cC280Rz2WgPCM97/wEfmvLZHlptNc3zjK3U/3PK/0aAVcGCDYz2t9r+uK7q9Ym2uOHBVW1d6+L7gR6b5LwR3l847J4rfJAP9+a35xGvTFPknFRDsTf4xFxhyCEgup1/nCVgkTm1gZqwL/nEakhtaKxgd6s/FwoOIf+cvpUmfUQT1Ldemr/S4vQejP25aAXohGHw171xGK85uEY6pUS/xApJUalxSv66szdF8TlbOiUawinn2KK3+BEfv9nGHIrzu+pdWXD6uTnK6bnoGt178tLk/3zx0ExE6+QfC8UU1T0VjDXO70Yiv3Ui8dLpqros4CkRnic/hCElYkZ0kYioSgffk/O2fBQW1IN+9cG22HkDhqhth/zmJaAwJk=
  siteKey: 6LffZOcUAAAAAPuQDgsqg9V1vJQMcK9vaoA6ksXN

title: "Health, Healing, and Hope (H3)"
twitter_username: ~
