---
description: "A journey of the peaks and valleys of health, healing, and hope."
email: laura@h3withlaura.com
facebook_URL: "https://www.facebook.com/lauramsanders/"
font-awesome-icon-logo: ~
github_username: ~
instagram_username: lauramsanders
logo-image-url: /images/android-chrome-192x192_Logo.png
markdown: kramdown
permalink: "/:categories/:year/:month/:day/:title:output_ext"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
staticman_url: "https://h3withlaura.herokuapp.com/v2/entry/rockmonkey4004/rockmonkey4004.github.io/master/comments"

reCaptcha:
  secret: Lmz6/f1PxtZx3Kg2FZbzTvrCxZHmIsO6OKgq39oo3hziDN2Ur63f7E31cUxnK4Wb4NSKrZRDDHx9gZ13kwlpTcmcPCqjj4DehGIRtNYCGbrShkoS5Mv0Mn6iTlNVh92mQCa+CD+2sR+etF7buZhAwrdPXpuVG8xmMjx9mQU4uvvb8Z13nsR2rC1k85e+YOCUtM5AybJa3sWfvzDkEKTl/JguHVJm2HDLYt7QcDQNVKhxmWfwvwANjXqtcyE8mF7yTeCBmQF+Rkq2t8fj3XrWeGUY+ipE5CJ/wJa9hQBwRByKgjSHS4NoC7lZdSmTvzZ87sJH6ZDprDRqwY8GbVKRtOpSgYnL9XguDj0+zik52M/yyaqPGaL2Xr5Qxys/nfMDF1PJhDZOpsyrqPqLFt9pB1lh+DH2dx8bsz5XWnDrbcOpItDkvR8AvyyWLirqyzVKZrFQekCD+eENtg+GmrTVRtegofWV6YxpsEoppX4QZb5yrg+p6YCEU8lWhVd52vp0WWU+T/CcruBpN1MneDOdCk3vyQP+8CPHUC/ySNy8adqU7Ee5v6R8g/5G1h77mIqr3gAi516e250iPITmbgUPdwm2XS3gfJ9nJWnEZxy3dgz8tMsHK9IxCRNWGFYfiKfKbx8fQuSn283yVeY0LBAYci4YCTX9Qw0UH3LSKkTnpXo=
  siteKey: 6LffZOcUAAAAAPuQDgsqg9V1vJQMcK9vaoA6ksXN

title: "Health, Healing, and Hope (H3)"
twitter_username: ~
