---
description: "A journey of the peaks and valleys of health, healing, and hope."
email: laura@h3withlaura.com
facebook_URL: "https://www.facebook.com/lauramsanders/"
font-awesome-icon-logo: ~
github_username: ~
instagram_username: lauramsanders
logo-image-url: /images/android-chrome-192x192_Logo.png
markdown: kramdown
permalink: "/:categories/:year/:month/:day/:title:output_ext"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
reCaptcha:
  secret: 6LffZOcUAAAAACMPIH2hzRK0tluaLPEs-PMqbRci
  siteKey: 6LffZOcUAAAAAPuQDgsqg9V1vJQMcK9vaoA6ksXN
staticman_url: "https://h3withlaura.herokuapp.com/v2/entry/rockmonkey4004/rockmonkey4004.github.io/master/comments"
title: "Health, Healing, and Hope (H3)"
twitter_username: ~
